//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObtelsaEntities : DbContext
    {
        public ObtelsaEntities()
            : base("name=ObtelsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<espectador> espectadors { get; set; }
        public virtual DbSet<localidad> localidads { get; set; }
        public virtual DbSet<localidad_disponible> localidad_disponible { get; set; }
        public virtual DbSet<propietario> propietarios { get; set; }
        public virtual DbSet<propietario_localidad> propietario_localidad { get; set; }
        public virtual DbSet<socio> socios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipo_espectador> tipo_espectador { get; set; }
        public virtual DbSet<tipo_identificacion> tipo_identificacion { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<ventanilla> ventanillas { get; set; }
    }
}
