//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad_disponible
    {
        public int lod_id { get; set; }
        public string lod_nombre { get; set; }
        public string lod_permitido { get; set; }
        public int lod_estado { get; set; }
    }
}
