//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propietario
    {
        public int pro_id { get; set; }
        public string tii_valor { get; set; }
        public string pro_identificacion { get; set; }
        public string pro_nombre { get; set; }
        public string loc_codigo { get; set; }
        public string pro_email { get; set; }
        public System.DateTime pro_fecha_creacion { get; set; }
        public System.DateTime pro_fecha_actualizacion { get; set; }
        public string pro_clave { get; set; }
        public int pro_estado { get; set; }
    
        public virtual localidad localidad { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
    }
}
