//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propietario_localidad
    {
        public int prl_id { get; set; }
        public int pro_id { get; set; }
        public string loc_codigo { get; set; }
        public int prl_disponible { get; set; }
        public int prl_emitido { get; set; }
        public string prl_contrato { get; set; }
        public System.DateTime prl_fecha_creacion { get; set; }
        public System.DateTime prl_fecha_actualizacion { get; set; }
        public int prl_estado { get; set; }
    }
}
