//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class socio
    {
        public int soc_id { get; set; }
        public string tii_valor { get; set; }
        public string soc_identificacion { get; set; }
        public string soc_nombre { get; set; }
        public string loc_codigo { get; set; }
        public string soc_email { get; set; }
        public string soc_contrato { get; set; }
        public int soc_asiento_maximo { get; set; }
        public int soc_asiento_emitido { get; set; }
        public int soc_pases_libres { get; set; }
        public int soc_pases_emitido { get; set; }
        public int soc_med_tarifa { get; set; }
        public int soc_med_tarifa_emitido { get; set; }
        public System.DateTime soc_fecha_creacion { get; set; }
        public System.DateTime soc_fecha_actualizacion { get; set; }
        public string soc_clave { get; set; }
        public int soc_estado { get; set; }
    
        public virtual localidad localidad { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
    }
}
