//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usu_id { get; set; }
        public string usu_identificacion { get; set; }
        public string usu_nombre { get; set; }
        public string usu_email { get; set; }
        public string usu_clave { get; set; }
        public Nullable<int> usu_asiento_maximo { get; set; }
        public Nullable<int> usu_asiento_emitido { get; set; }
        public Nullable<System.DateTime> usu_fecha_emision { get; set; }
        public string usu_certificado { get; set; }
        public string tii_valor { get; set; }
        public string tie_valor { get; set; }
        public string loc_codigo { get; set; }
    
        public virtual localidad localidad { get; set; }
        public virtual tipo_espectador tipo_espectador { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
    }
}
