//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventanilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ventanilla()
        {
            this.espectadors = new HashSet<espectador>();
        }
    
        public int ven_id { get; set; }
        public string ven_nombre { get; set; }
        public Nullable<int> ven_aforo_maximo { get; set; }
        public Nullable<int> ven_aforo_emitido { get; set; }
        public string ven_jornada { get; set; }
        public Nullable<System.DateTime> ven_horainicio { get; set; }
        public Nullable<System.DateTime> ven_horafinal { get; set; }
        public Nullable<int> ven_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<espectador> espectadors { get; set; }
    }
}
